version: '3.7'
services:
  mongodb_container:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped

volumes:
  mongodb_data_container: